---
# vars file for role-kubeapps
kubeapps_k8s_ingress_class: traefik
letsencrypt_staging: https://acme-staging-v02.api.letsencrypt.org/directory
letsencrypt_prod: https://acme-v02.api.letsencrypt.org/directory

letsencrypt_envs:
  staging: '{{ letsencrypt_staging }}'
  prod: '{{ letsencrypt_prod }}'

letsencrypt_envs_ca_certs:
  staging: https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem

# Mounted in acme internal
kubeapps_internal_acme_ca_file: /etc/ssl/certs/acmeca.crt
kubeapps_internal_acme_ca_in_volume_crt: /etc/ssl/certs/acmeca.crt
kubeapps_internal_acme_ca_extra_volumes: []
kubeapps_internal_acme_ca_extra_volumes_mounts: []

ingress_hosts_internals: 
  - "{{ dex_hostname }}"
  - "{{ kubeapps_hostname }}"
  - "{{ api_waypoint_hostname }}"

ingress_hosts_internals_joined: "{{ ingress_hosts_internals | join(' ') }}"