---
- name: Download certificate file
  uri:
    url: "{{ cert_manager_staging_ca_cert_url }}"
    validate_certs: "{{ kubeapps_internal_acme_network_ip is none }}"
    return_content: True
  register: ca_file

- name: Trust cert inside current machine
  ansible.builtin.copy:
    dest: "{{ kubeapps_internal_acme_ca_file }}"
    content: "{{ ca_file.content }}"

- set_fact:
    kubeapps_internal_acme_ca_content: "{{ ca_file.content }}"
    kubeapps_internal_acme_ca_extra_volumes:
    - name: acme-internal-ca-share
      configMap: 
        name: acme-internal-ca-share
    kubeapps_internal_acme_ca_extra_volumes_mounts:
      - name: acme-internal-ca-share
        mountPath: "{{ kubeapps_internal_acme_ca_in_volume_crt }}"
        subPath: ca.crt
