#cloud-config

datasource:
  Azure:
    apply_network_config: true
    data_dir: /var/lib/waagent
    disk_aliases:
      ephemeral0: /dev/disk/cloud/azure_resource

runcmd:
  - [sleep, 20]

ansible:
  install_method: pip
  package_name: ansible
  setup_controller:
    run_ansible:
      - playbook_dir: /playbook
        inventory: /playbook/inventories/azure/hosts
        playbook_name: site.yaml
        extra_vars: "vault_url=${vault_url}
           dex_github_client_org=${dex_github_client_org}
           dex_github_client_team=${dex_github_client_team}
           cert_manager_letsencrypt_env=${cert_manager_letsencrypt_env}
           kubeapps_hostname=${kubeapps_hostname}
           dex_hostname=${dex_hostname} -o 'IdentitiesOnly=yes'"
        connection: local
